using Biohazard.BioRand.RE7.Items;
using Biohazard.BioRand.RE7.REEngine;
using Enums.app.GameFlowFsmManager;
using Enums.app.Item;
using IntelOrca.Biohazard.BioRand;

namespace Biohazard.BioRand.RE7.Modifiers;

internal class ItemDropTableModifier : Modifier {
    private const string RandomizerKey = "modifier/item-drops";
    private static readonly ItemDefinitionRepository _itemDefinitions = ItemDefinitionRepository.Default;

    private readonly List<(GameFlowKindEnum, string)> _dropTableFiles = new(){
        (GameFlowKindEnum.C03_1_Main, PakPath.UserFile("prefab/item/reliefitemtable_03_01_0000.user")),
        (GameFlowKindEnum.C03_2_Main, PakPath.UserFile("prefab/item/reliefitemtable_03_02_0000.user")),
        (GameFlowKindEnum.C03_2_Main, PakPath.UserFile("prefab/item/reliefitemtable_03_02_0600.user")),
        (GameFlowKindEnum.C03_3_Main, PakPath.UserFile("prefab/item/reliefitemtable_03_03_0000.user")),
        (GameFlowKindEnum.C03_3_Main, PakPath.UserFile("prefab/item/reliefitemtable_03_03_1000.user")),
        (GameFlowKindEnum.C03_4_Main, PakPath.UserFile("prefab/item/reliefitemtable_03_04_0000.user")),
        (GameFlowKindEnum.C03_5_Main, PakPath.UserFile("prefab/item/reliefitemtable_03_05_0000.user")),
        (GameFlowKindEnum.C04_1_Main, PakPath.UserFile("prefab/item/reliefitemtable_04_01_0000.user")),
        (GameFlowKindEnum.C04_2_Main, PakPath.UserFile("prefab/item/reliefitemtable_04_02_0000.user")),
        (GameFlowKindEnum.C04_3_Main, PakPath.UserFile("prefab/item/reliefitemtable_04_02_0500.user")),
        (GameFlowKindEnum.C04_3_Main, PakPath.UserFile("prefab/item/reliefitemtable_04_03_0000.user")),
    };

    public override void LogState(Randomizer randomizer, RandomizerLogger logger) {
        logger.Push("Original item drop tables");
        foreach (var (chapter, path) in _dropTableFiles) {
            logger.Push(chapter.ToString().Without("_Main"));
            var deserialized = randomizer.FileRepository.DeserializeUserFile<ItemDropTable>(path)
                               ?? throw new RandomizerUserException(
                                   $"Failed to deserialize {path}! Report this please.");

            deserialized.Log(logger);
            logger.Pop();
        }

        logger.Pop();
    }

    private ItemDropTable ConstructItemDropTable(Randomizer randomizer, GameFlowKindEnum chapter, string path) {
        var result = new ItemDropTable(){
            _Comment = $"Generated by BioRand for chapter {chapter}."
        };

        var itemRandomizer = randomizer.ItemRandomizer;
        var ammoOnlyAvailableWeapons = randomizer.GetConfigOption<bool>("item-drop-ammo-only-available-weapons");
        var min = randomizer.GetConfigOption("item-drop-ammo-min", 0.1);
        var max = randomizer.GetConfigOption("item-drop-ammo-max", 1.0);
        var rng = randomizer.GetRng(RandomizerKey, chapter, path);

        foreach (var id in ItemDrops.GenericRuntimeDrops) {
            var idStr = id.ToString();
            var item = _itemDefinitions.FromId(idStr)!;

            var rate = randomizer.GetConfigOption<double>($"item-drop-ratio-{idStr.ToLowerInvariant()}");
            if (rate <= 0)
                continue;

            if (ammoOnlyAvailableWeapons
                && item.CategoryType == ItemCategoryType.Shell
                && itemRandomizer.ChapterAmmoMap.TryGetValue(chapter, out var allowedAmmo)
                && !allowedAmmo.Contains(id)) {
                continue;
            }

            var ratePct = (uint)(rate * 100.0);
            var (easyDropAmount, normalDropAmount, madhouseDropAmount) =
                itemRandomizer.DetermineDropAmount(id, min, max, rng);

            result.DataList.Add(new ItemDropDistribution(){
                ItemID = idStr,
                EasyDropRate = ratePct,
                NormalDropRate = ratePct,
                HardDropRate = ratePct,
                ReliefNum = easyDropAmount,
                NormalDropNum = normalDropAmount,
                ReliefDropNum = madhouseDropAmount
            });
        }

        foreach (var valuableDrop in itemRandomizer.GetValuableDrops(rng, "item-drop")) {
            var drop = valuableDrop.Item;
            result.DataList.Add(new ItemDropDistribution(){
                ItemID = drop.Id,
                EasyDropRate = valuableDrop.DropRate,
                NormalDropRate = valuableDrop.DropRate,
                HardDropRate = valuableDrop.DropRate,
                ReliefNum = (uint)drop.CountEasy,
                NormalDropNum = (uint)drop.CountNormal,
                ReliefDropNum = (uint)drop.CountMadhouse
            });
        }

        return result;
    }

    public override void Apply(Randomizer randomizer, RandomizerLogger logger) {
        foreach (var (chapter, path) in _dropTableFiles) {
            var dropTable = ConstructItemDropTable(randomizer, chapter, path);

            logger.Push($"Modified item drop table ({chapter})");
            dropTable.Log(logger);
            logger.Pop();

            randomizer.FileRepository.ModifyUserFile<ItemDropTable>(path, _ => dropTable);
        }
    }
}