using app;
using Biohazard.BioRand.RE7.Items;
using Enums.app;
using Enums.app.Item;

namespace Biohazard.BioRand.RE7.Modifiers;

internal class RecipeModifier : Modifier
{
    // The combine GUI only allows 20 slots, even in a modded state (4 cols, 5 rows).
    // REFramework is required for this -> scripts/reframework/autorun/
    public const int MaxRecipeCount = 20;

    private const string RandomizerKey = "recipes";
    private static readonly string DictionaryCombineDataPath = PakPath.Of("prefab/item/dictionarycombinedata.user.2");
    private static readonly string ItemCombineDataPath = PakPath.Of("prefab/item/itemcombinedata.user.2");

    private static readonly ItemDefinitionRepository itemDefinitions = ItemDefinitionRepository.Default;
    private List<Recipe> originalRecipes = new();
    private List<DictionaryCombineData.Data> originalDictCombineData = new();

    public override void LogState(RE7Randomizer randomizer, RandomizerLogger logger)
    {
        originalRecipes = randomizer.FileRepository.DeserializeUserFile<ItemCombineData>(ItemCombineDataPath)._Datas;
        originalDictCombineData = randomizer.FileRepository.DeserializeUserFile<DictionaryCombineData>(DictionaryCombineDataPath)._Datas;

        logger.Push("Original crafting recipes");

        foreach (var recipe in originalRecipes)
            logger.LogLine(itemDefinitions.FormatRecipe(recipe));

        logger.Pop();
    }

    public override void Apply(RE7Randomizer randomizer, RandomizerLogger logger)
    {
        var addNewRecipes = randomizer.GetConfigOption<bool>("recipes-add-new");
        var replaceOriginalRecipes = randomizer.GetConfigOption<bool>("recipes-replace-original");

        if (!addNewRecipes && !replaceOriginalRecipes)
            return;

        var mode = randomizer.GetConfigOption<string>("recipes-randomization-mode");
        var rng = randomizer.GetRng(RandomizerKey);
        var pool = mode switch
        {
            "easy" => CreateEasyPool(rng),
            "balanced" => CreateBalancedPool(rng),
            "chaos" => CreateChaosPool(rng),
            "crazy" => CreateCrazyPool(rng),
            _ => throw new NotImplementedException($"Invalid recipe randomization mode {mode} supplied!")
        };

        var addedRecipes = new List<Recipe>();
        if (addNewRecipes)
        {
            var min = randomizer.GetConfigOption<int>("recipe-new-min");
            var max = randomizer.GetConfigOption<int>("recipe-new-max");
            var amount = rng.Next(min, max);

            for (var i = 0; i < amount; i++)
            {
                var recipe = rng.Next(pool);
                AddRecipe(randomizer, recipe);
                addedRecipes.Add(recipe);
            }
        }

        if (replaceOriginalRecipes)
        {
            ReplaceOriginalRecipes(randomizer, rng, pool);
        }

        // Rebuild dictionarycombinedata.user.2
        // This file holds the result item IDs of the items that are displayed in the combine GUI.
        RebuildDictionary(randomizer, addedRecipes);

        // Finally, write the spoiler log.
        logger.Push("New crafting recipes");

        foreach (var newRecipe in addedRecipes)
            logger.LogLine(itemDefinitions.FormatRecipe(newRecipe));

        logger.Pop();
    }

    private static void RebuildDictionary(RE7Randomizer randomizer, List<Recipe> newRecipes)
    {
        randomizer.FileRepository.ModifyUserFile<DictionaryCombineData>(
            DictionaryCombineDataPath,
            root =>
            {
                root._Datas.Clear();

                for (int i = 0; i < newRecipes.Count && i < MaxRecipeCount; i++)
                {
                    root._Datas.Add(new DictionaryCombineData.Data { ItemDataID = newRecipes[i].ResultItemID });
                }

                return root;
            });
    }

    private static Recipe CreateRecipeByIds(
        int srcItem1Count,
        string srcItemId1,
        int srcItem2Count,
        string srcItemId2,
        int resultItemCount,
        string resultItemId
    )
        => new Recipe()
        {
            _Comment = "Generated by BioRand.",
            DataID = $"{resultItemId}",
            SrcItemID1 = srcItemId1,
            SrcItemNum1 = srcItem1Count,
            SrcItemID2 = srcItemId2,
            SrcItemNum2 = srcItem2Count,
            ResultItemID = resultItemId,
            ResultItemNum = resultItemCount,
            EnableFlag = Guid.Empty,
            IsTutorialTarget = true, // TODO What exactly is this?
            IsTrophyTarget = true, // TODO What exactly is this?
        };

    private static Recipe CreateRecipeByNames(
        int combine,
        string srcItemId1,
        int with,
        string srcItemId2,
        int toGet,
        string resultItemId
    ) => CreateRecipeByIds(
            combine,
            itemDefinitions.GetId(srcItemId1),
            with,
            itemDefinitions.GetId(srcItemId2),
            toGet,
            itemDefinitions.GetId(resultItemId)
        );

    private readonly List<ItemCategoryType> typeBlacklist = new()
    {
        ItemCategoryType.KeyItem, ItemCategoryType.DiscardableKeyItem, ItemCategoryType.UsableKeyItem,
        ItemCategoryType.Map, ItemCategoryType.File
    };

    private readonly List<Recipe> easyModeRecipePool = new()
    {
        // ======== Ammo ========
        CreateRecipeByNames(combine: 20, "Enhanced Handgun Ammo", with: 2, "Gunpowder", toGet: 15, "Shotgun Shells"),
        CreateRecipeByNames(combine: 30, "Machine Gun Ammo", with: 20, "Handgun Ammo", toGet: 5, "44 MAG Ammo"),
        CreateRecipeByNames(combine: 10, "Shotgun Shells", with: 2, "Gunpowder", toGet: 5, "44 MAG Ammo"),
        CreateRecipeByNames(combine: 20, "Enhanced Handgun Ammo", with: 1, "Strong Chem Fluid", toGet: 10, "44 MAG Ammo"),
        CreateRecipeByNames(combine: 1, "Neuro Rounds", with: 1, "Chem Fluid", toGet: 1, "Flame Rounds"),
        CreateRecipeByNames(combine: 1, "Flame Rounds", with: 1, "Chem Fluid", toGet: 1, "Neuro Rounds"),

        // ======== Heal ========
        CreateRecipeByNames(combine: 1, "First Aid Med", with: 1, "First Aid Med", toGet: 1, "Strong First Aid Med"),
        CreateRecipeByNames(combine: 1, "Strong First Aid Med", with: 1, "Separating Agent", toGet: 2, "First Aid Med"),
        CreateRecipeByNames(combine: 1, "Strong Chem Fluid", with: 1, "First Aid Med", toGet: 1, "Strong First Aid Med"),
        CreateRecipeByNames(combine: 1, "Psychostimulants", with: 1, "Herb", toGet: 1, "First Aid Med"),

        // ======== Drugs ========
        CreateRecipeByNames(combine: 10, "44 MAG Ammo", with: 1, "Strong First Aid Med", toGet: 1, "Steroids"),
        CreateRecipeByNames(combine: 10, "Shotgun Shells", with: 1, "Strong First Aid Med", toGet: 1, "Stabilizer")
    };

    private List<Recipe> CreateEasyPool(Rng rng)
    {
        var balanced = new List<Recipe>();
        var mixedPool = easyModeRecipePool.OrderBy(_ => rng.Next()).ToList();

        foreach (var recipe in mixedPool)
        {
            //if (!balanced.Any(r => r.ResultItemID == recipe.ResultItemID))
            balanced.Add(recipe);
        }

        return balanced;
    }

    private static List<Recipe> CreateBalancedPool(Rng rng)
    {
        // TODO
        var recipes = new List<Recipe>();
        return recipes;
    }

    private static List<Recipe> CreateChaosPool(Rng rng)
    {
        // TODO
        var recipes = new List<Recipe>();
        return recipes;
    }

    private List<Recipe> CreateCrazyPool(Rng rng)
    {
        var crazyItems = new List<string> {
            ItemID.EthanLeg.ToString(),
            ItemID.HandCutOff.ToString(),
            ItemID.ChainCutter.ToString(),
            ItemID.EntranceHallKey.ToString(),
            ItemID.FlameBulletS.ToString(),
            ItemID.HandAxe.ToString(),
            ItemID.MiaDriversLicense.ToString(),
            ItemID.SerumMaterialA.ToString(),
            ItemID.SerumMaterialB.ToString(),
            ItemID.Magnum.ToString(),
            "Coin", // Antique coin
            "CoinOld" // Dirty coin
        };

        var valid = itemDefinitions
            .Where(i => crazyItems.Contains(i.Id))
            .ToList();

        var recipes = new List<Recipe>();

        foreach (var result in valid)
        {
            if (valid.Count < 2)
                break;

            var src1 = rng.Next(valid);
            var src2 = rng.Next(valid);

            var recipe = CreateRecipeByIds(
                rng.Next(1, 1000), src1.Id,
                rng.Next(1, 1000), src2.Id,
                rng.Next(1, 1000), result.Id
            );

            recipes.Add(recipe);
        }

        return recipes
            .GroupBy(r => r.ResultItemID)
            .Select(g => g.First())
            .ToList();
    }

    private static void AddRecipe(RE7Randomizer randomizer, Recipe recipe)
    {
        randomizer.FileRepository.ModifyUserFile<ItemCombineData>(ItemCombineDataPath, root =>
        {
            root._Datas.Add(recipe);
            return root;
        });
    }

    private void ReplaceOriginalRecipes(RE7Randomizer randomizer, Rng rng, List<Recipe> pool)
    {
        randomizer.FileRepository.ModifyUserFile<ItemCombineData>(ItemCombineDataPath, root =>
        {
            var updatedRecipes = root._Datas;
            for (int i = updatedRecipes.Count - 1; i >= 0; i--)
            {
                var recipe = updatedRecipes[i];
                if (!originalRecipes.Contains(recipe))
                    continue;

                if (recipe.ResultItemID == ItemID.DybbukMedicine.ToString()) // Prevent Evie sample softlock
                    continue;

                updatedRecipes[i] = rng.Next(pool);
            }

            root._Datas = updatedRecipes;
            return root;
        });
    }
}