<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Biohazard.BioRand.RE7\Biohazard.BioRand.RE7.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="_Data/**/*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="_Data\EmbeddedResource.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="EmbeddedResource.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" Version="0.53.1" />
  </ItemGroup>

</Project>
