<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Biohazard.BioRand.RE7</RootNamespace>
        <Nullable>enable</Nullable>
        <DefineConstants>$(DefineConstants);ENABLE_BETA_FEATURES</DefineConstants>
        <PlatformTarget>x64</PlatformTarget>
        <ReeutilsProjectPath>..\reeutils\src\IntelOrca.Biohazard.REE\IntelOrca.Biohazard.REE.csproj</ReeutilsProjectPath>
        <UseReeutilsProjectReference
            Condition="'$(UseReeutilsProjectReference)' == '' and Exists('$(ReeutilsProjectPath)')">
            true
        </UseReeutilsProjectReference>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CsvHelper" Version="33.1.0" />
        <PackageReference Include="IntelOrca.Biohazard.BioRand.Common" Version="1.6.1" />
        <PackageReference Include="IntelOrca.Biohazard.BioRand.REE" Version="1.6.1" />
        <PackageReference Include="IntelOrca.Biohazard.REE" Version="1.4.7"
                          Condition="'$(UseReeutilsProjectReference)' != 'true'" />
        <PackageReference Include="RectangleBinPacking" Version="1.0.2" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="_Data/**/*" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference
            Include="..\Biohazard.BioRand.RE7.REFrameworkPlugins\Biohazard.BioRand.RE7.REFrameworkPlugins.csproj" />
        <ProjectReference Include="$(ReeutilsProjectPath)" Condition="'$(UseReeutilsProjectReference)' == 'true'" />
    </ItemGroup>
</Project>