<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>BioHazard.BioRand.RE7</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Biohazard.BioRand.RE7\Biohazard.BioRand.RE7.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="IntelOrca.Biohazard.REE" Version="1.4.7" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.1-alpha.0.7" />
  </ItemGroup>
</Project>
