import re
import sys
from pathlib import Path

NAMESPACE_REGEX = re.compile(r'namespace\s+([a-zA-Z0-9_:]+)\s*\{')
ENUM_REGEX = re.compile(r'enum(?:\s+class)?\s+([a-zA-Z0-9_]+)\s*\{')
ENUM_VALUE_REGEX = re.compile(r'^\s*([a-zA-Z0-9_]+)\s*(=\s*([^,]+))?\s*,?\s*$')

CSHARP_KEYWORDS = {
    "internal", "public", "private", "protected",
    "class", "struct", "enum", "namespace",
    "event", "base", "void", "int", "uint",
    "string", "object", "ref", "out", "in"
}


def escape_csharp_identifier(name: str, cpp_namespace: str) -> str:
    if name in CSHARP_KEYWORDS:
        print(f"[!] Escaping C# keyword {name} in namespace {cpp_namespace}")
        return f"@{name}"
    return name


def convert_namespace(cpp_namespace: str) -> str:
    parts = cpp_namespace.split("::")
    parts = [escape_csharp_identifier(p, cpp_namespace) for p in parts]
    return ".".join(parts)


def parse_enums(lines):
    results = []
    namespace_stack = []
    i = 0

    while i < len(lines):
        line = lines[i]

        ns_match = NAMESPACE_REGEX.search(line)
        if ns_match:
            namespace_name = ns_match.group(1)
            namespace_stack.append(namespace_name)
            i += 1
            continue

        if "}" in line and namespace_stack:
            namespace_stack.pop()
            i += 1
            continue

        enum_match = ENUM_REGEX.search(line)
        if enum_match:
            enum_name = enum_match.group(1)
            enum_values = []
            requires_uint = False

            i += 1
            while i < len(lines):
                enum_line = lines[i]

                if "};" in enum_line or enum_line.strip() == "}":
                    break

                value_match = ENUM_VALUE_REGEX.match(enum_line)
                if value_match:
                    name = value_match.group(1)
                    raw_value = value_match.group(3)

                    if raw_value:
                        raw_value = raw_value.strip()

                        try:
                            if raw_value.startswith("0x"):
                                numeric = int(raw_value, 16)
                            else:
                                numeric = int(raw_value)

                            if numeric > 0x7FFFFFFF:
                                print(f"[!] Integer overflow for enumerator {name} in enum {enum_name}, using uint")
                                requires_uint = True
                                raw_value = hex(numeric) + "u"
                        except ValueError:
                            pass

                        enum_values.append((name, raw_value))
                    else:
                        enum_values.append((name, None))

                i += 1

            full_namespace = ".".join(
                convert_namespace(ns) for ns in namespace_stack
            )

            results.append({
                "namespace": full_namespace,
                "enum_name": enum_name,
                "values": enum_values,
                "requires_uint": requires_uint
            })

        i += 1

    return results


def generate_csharp(enums):
    output = [
        "// This code was generated by scripts\\convert_enums_to_cs.py.\n",
        "#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters",
        "#pragma warning disable CA1069 // Enums should not have duplicate values",
        "#pragma warning disable IDE1006 // These words must begin with upper case characters",
        "#pragma warning disable IDE0130 // Namespace does not match folder structure",
        "\n"
    ]

    for enum in enums:
        if enum["namespace"]:
            if re.match(r'^System(\.|$)', str(enum["namespace"])):
                print(f"[!] Not generating enum {enum["namespace"]} from System namespace")
                continue
            
            output.append(f"namespace Enums.{enum['namespace']}")
            output.append("{")

        underlying = " : uint" if enum["requires_uint"] else ""

        output.append(f"    public enum {enum['enum_name']}{underlying}")
        output.append("    {")

        for name, value in enum["values"]:
            if value:
                output.append(f"        {name} = {value},")
            else:
                output.append(f"        {name},")

        output.append("    }")

        if enum["namespace"]:
            output.append("}")

        output.append("")

    return "\n".join(output)


def convert_file(input_path: Path, output_path: Path):
    lines = input_path.read_text(encoding="utf-8").splitlines()
    enums = parse_enums(lines)
    csharp_code = generate_csharp(enums)
    output_path.write_text(csharp_code, encoding="utf-8")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python convert_enums.py input.hpp output.cs")
        sys.exit(1)

    input_file = Path(sys.argv[1])
    output_file = Path(sys.argv[2])

    convert_file(input_file, output_file)
    print(f"[+] Converted {input_file} -> {output_file}")
