<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="application">
      <HintPath>lib\REFramework.NET.application.dll</HintPath>
    </Reference>
    <Reference Include="AssemblyGenerator">
      <HintPath>lib\AssemblyGenerator.dll</HintPath>
    </Reference>
    <Reference Include="Hexa.NET.ImGui">
      <HintPath>lib\Hexa.NET.ImGui.dll</HintPath>
    </Reference>
    <Reference Include="HexaGen.Runtime">
      <HintPath>lib\HexaGen.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis">
      <HintPath>lib\Microsoft.CodeAnalysis.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.CSharp">
      <HintPath>lib\Microsoft.CodeAnalysis.CSharp.dll</HintPath>
    </Reference>
    <Reference Include="REFCoreDeps">
      <HintPath>lib\REFCoreDeps.dll</HintPath>
    </Reference>
    <Reference Include="REFramework.NET">
      <HintPath>lib\REFramework.NET.dll</HintPath>
    </Reference>
    <Reference Include="viacore">
      <HintPath>lib\REFramework.NET.viacore.dll</HintPath>
    </Reference>
    <Reference Include="_System">
      <HintPath>lib\REFramework.NET._System.dll</HintPath>
    </Reference>
    <Reference Include="_System.Core">
      <HintPath>lib\REFramework.NET._System.Core.dll</HintPath>
    </Reference>
    <Reference Include="_mscorlib">
      <HintPath>lib\REFramework.NET._mscorlib.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <ItemGroup>
    <PluginSourceFile Include="$(MSBuildProjectDirectory)\**\*.cs" Exclude="$(MSBuildProjectDirectory)\bin\**;$(MSBuildProjectDirectory)\obj\**" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="IntelOrca.Biohazard.REE" Version="1.4.8" />
  </ItemGroup>

  <PropertyGroup>
    <RandomizerProjectDirectory>$(MSBuildProjectDirectory)\..\Biohazard.BioRand.RE7</RandomizerProjectDirectory>
    <RandomizerPluginOutputPath>$(RandomizerProjectDirectory)\bin\$(Configuration)\$(TargetFramework)\plugins\$(AssemblyName).dll</RandomizerPluginOutputPath>
    <RandomizerPluginDataPath>$(RandomizerProjectDirectory)\_Data\$(AssemblyName).dll</RandomizerPluginDataPath>
  </PropertyGroup>

  <Target Name="CopyToRandomizerOutput"
          AfterTargets="Build"
          Inputs="@(PluginSourceFile)"
          Outputs="$(RandomizerPluginOutputPath);$(RandomizerPluginDataPath)">
    <Copy
      SourceFiles="$(TargetPath)"
      DestinationFiles="$(RandomizerPluginOutputPath)" />
    <Copy
      SourceFiles="$(TargetPath)"
      DestinationFiles="$(RandomizerPluginDataPath)" />
  </Target>
</Project>
