<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="application">
      <HintPath>lib\REFramework.NET.application.dll</HintPath>
    </Reference>
    <Reference Include="REFramework.NET">
      <HintPath>lib\REFramework.NET.dll</HintPath>
    </Reference>
    <Reference Include="viacore">
      <HintPath>lib\REFramework.NET.viacore.dll</HintPath>
    </Reference>
    <Reference Include="_System">
      <HintPath>lib\REFramework.NET._System.dll</HintPath>
    </Reference>
    <Reference Include="_System.Core">
      <HintPath>lib\REFramework.NET._System.Core.dll</HintPath>
    </Reference>
    <Reference Include="_mscorlib">
      <HintPath>lib\REFramework.NET._mscorlib.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
